
import React, { useRef } from 'react';
import { Shield, Clock, FileText, Lock, ChevronRight, Activity, Zap, Award, Upload, FileJson } from 'lucide-react';
import { CertificateData } from '../types';

interface Props {
  onStartWipe: () => void;
  recentCertificates: CertificateData[];
  onViewCert: (cert: CertificateData) => void;
  onImportCert: (cert: CertificateData) => void;
}

const Dashboard: React.FC<Props> = ({ onStartWipe, recentCertificates, onViewCert, onImportCert }) => {
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        try {
          const cert = JSON.parse(event.target?.result as string);
          if (cert.id && cert.fileName) {
            onImportCert(cert);
          } else {
            alert("Error: Invalid SWC Certificate JSON. Please ensure the file was generated by SecureWiper.");
          }
        } catch (err) {
          alert("Error: Unable to parse JSON file. File may be corrupted.");
        }
      };
      reader.readAsText(file);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-10 animate-in fade-in duration-700">
      {/* Analytics Overview */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <div className="flex items-center gap-4">
            <div className="bg-blue-50 p-3 rounded-xl text-blue-600">
              <Shield size={24} />
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Compliance Standard</p>
              <p className="text-lg font-bold text-slate-800">NIST SP 800-88 R1</p>
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <div className="flex items-center gap-4">
            <div className="bg-indigo-50 p-3 rounded-xl text-indigo-600">
              <FileJson size={24} />
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Stored Audits</p>
              <p className="text-lg font-bold text-slate-800">{recentCertificates.length} Certificates</p>
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <div className="flex items-center gap-4">
            <div className="bg-emerald-50 p-3 rounded-xl text-emerald-600">
              <Activity size={24} />
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">System Status</p>
              <p className="text-lg font-bold text-slate-800">Ready for Audit</p>
            </div>
          </div>
        </div>
      </div>

      {/* Main Action Hub */}
      <div className="bg-slate-900 rounded-[2.5rem] p-10 md:p-16 text-white relative overflow-hidden shadow-2xl border border-slate-800">
        <div className="relative z-10 max-w-2xl">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/30 text-blue-400 text-[10px] font-black uppercase tracking-[0.25em] mb-8">
            SecureWiper Enterprise v2.5
          </div>
          <h1 className="text-5xl md:text-7xl font-black mb-8 tracking-tighter leading-[0.9]">
            Convert <span className="text-blue-500 italic">JSON</span> to forensic <span className="text-indigo-400 underline decoration-indigo-500/30">PDF</span>.
          </h1>
          <p className="text-slate-400 text-xl mb-12 leading-relaxed font-medium">
            Upload your sanitization logs to generate a high-fidelity, NIST-compliant certificate suitable for legal and corporate audits.
          </p>
          <div className="flex flex-col sm:flex-row gap-5">
            <button 
              onClick={() => fileInputRef.current?.click()}
              className="group bg-blue-600 hover:bg-blue-500 text-white px-10 py-6 rounded-2xl font-black text-xl flex items-center justify-center gap-4 transition-all shadow-xl shadow-blue-600/30 active:scale-95 border-b-4 border-blue-800"
            >
              <Upload size={28} />
              Convert JSON to PDF
            </button>
            <button 
              onClick={onStartWipe}
              className="bg-slate-800 hover:bg-slate-700 text-slate-300 px-10 py-6 rounded-2xl font-bold text-lg flex items-center justify-center gap-4 transition-all active:scale-95 border-b-4 border-slate-950"
            >
              <Lock size={24} />
              New Sanitization
            </button>
            <input 
              type="file" 
              accept=".json" 
              className="hidden" 
              ref={fileInputRef} 
              onChange={handleFileUpload} 
            />
          </div>
        </div>
        
        {/* Background Accents */}
        <div className="absolute -top-24 -right-24 opacity-5 pointer-events-none scale-150">
          <Shield size={600} strokeWidth={0.5} />
        </div>
        <div className="absolute bottom-10 right-10 flex gap-1 items-end">
          {[0.2, 0.4, 0.6, 0.8, 1.0].map((o, i) => (
            <div key={i} className="w-1 bg-blue-500/20" style={{ height: `${20 + i * 20}px`, opacity: o }}></div>
          ))}
        </div>
      </div>

      {/* Audit History */}
      <div className="bg-white rounded-[2rem] border border-slate-200 overflow-hidden shadow-sm">
        <div className="px-8 py-6 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
          <h3 className="text-lg font-black text-slate-800 flex items-center gap-3 uppercase tracking-wider">
            <Clock className="text-blue-500" size={20} />
            Certification Audit Trail
          </h3>
          <span className="text-xs font-bold text-slate-400">{recentCertificates.length} Records found</span>
        </div>
        
        {recentCertificates.length > 0 ? (
          <div className="divide-y divide-slate-100">
            {recentCertificates.map((cert) => (
              <div 
                key={cert.id}
                onClick={() => onViewCert(cert)}
                className="px-8 py-6 flex items-center justify-between hover:bg-blue-50/30 cursor-pointer transition-all group"
              >
                <div className="flex items-center gap-6">
                  <div className="w-14 h-14 bg-slate-100 rounded-2xl flex items-center justify-center text-slate-400 group-hover:bg-blue-600 group-hover:text-white group-hover:rotate-6 transition-all shadow-sm">
                    <FileText size={28} />
                  </div>
                  <div>
                    <p className="font-black text-slate-900 text-lg tracking-tight group-hover:text-blue-700 transition-colors">{cert.fileName}</p>
                    <div className="flex items-center gap-3 mt-1">
                      <span className="text-[10px] font-mono font-bold text-slate-400 bg-slate-100 px-2 py-0.5 rounded">{cert.id}</span>
                      <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{cert.passes} Cycles</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-10">
                  <div className="hidden md:block text-right">
                    <p className="text-sm font-bold text-slate-700">{new Date(cert.wipeDate).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</p>
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Forensic Date</p>
                  </div>
                  <div className="bg-emerald-100 text-emerald-700 px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-[0.15em] border border-emerald-200 shadow-sm">
                    Verified
                  </div>
                  <ChevronRight className="text-slate-300 group-hover:text-blue-500 group-hover:translate-x-1 transition-all" />
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="p-24 text-center space-y-6">
            <div className="bg-slate-50 w-24 h-24 rounded-full flex items-center justify-center mx-auto text-slate-200 border-2 border-dashed border-slate-200">
              <FileJson size={48} />
            </div>
            <div className="max-w-xs mx-auto">
              <p className="text-xl font-black text-slate-800">Vault Empty</p>
              <p className="text-slate-500 text-sm mt-2">No certificates found. Use the JSON converter or run a new sanitization to generate records.</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Dashboard;
